trigger:
- main

parameters:
  - name: environment
    displayName: "Select Environment"
    type: string
    default: "dev"
    values:
      - dev
      - qa
      - uat
      - prod

variables:
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  APP_NAME: 'myappmulti'
  manifestsPath: '$(Build.SourcesDirectory)/manifests/'
  IMAGE_REPOSITORY: 'myappmulti'

stages:
- stage: BuildAndPush
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build and Push Docker Image to ACR
    pool: default
    variables:
      - ${{ if eq(parameters.environment, 'dev') }}:
        - group: dev-variables
      - ${{ if eq(parameters.environment, 'qa') }}:
        - group: qa-variables
      - ${{ if eq(parameters.environment, 'uat') }}:
        - group: uat-variables
      - ${{ if eq(parameters.environment, 'prod') }}:
        - group: prod-variables
    steps:
    - task: Docker@2
      displayName: Build and Push Docker Image
      inputs:
        command: buildAndPush
        repository: $(CONTAINER_REGISTRY)/$(IMAGE_REPOSITORY)  # ACR registry + image name
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)  # Use the service connection name directly
        tags: |
          $(tag)
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Kubernetes Manifests'
      inputs:
        PathtoPublish: '$(manifestsPath)'
        ArtifactName: 'kube-manifest'
        publishLocation: 'Container'
    - task: Bash@3
      displayName: Replace placeholders in deployment.yaml
      inputs:
        targetType: 'inline'
        script: |
         echo "APP_NAME is: $(APP_NAME)"
         sed -i "s,{{APP_NAME}},${APP_NAME},g" $(Build.SourcesDirectory)/manifests/deployment.yaml
         sed -i "s,{{ENVIRONMENT}},${ENVIRONMENT},g" $(Build.SourcesDirectory)/manifests/deployment.yaml
         sed -i "s,APP_IMAGE_NAME,${ACR_NAME}.azurecr.io/${APP_NAME}:${IMAGE_TAG},g" $(Build.SourcesDirectory)/manifests/deployment.yaml

    - task: Bash@3
      displayName: Debug Deployment YAML deployment.yaml
      inputs:
        targetType: 'inline'
        script: |
         cat $(Build.SourcesDirectory)/manifests/deployment.yaml
         displayName: 'Debug Deployment YAML'

    - task: Bash@3
      displayName: Replace placeholders in service.yaml
      inputs:
        targetType: 'inline'
        script: |
          sed -i "s,{{APP_NAME}},${APP_NAME},g" $(Build.SourcesDirectory)/manifests/service.yaml
          sed -i "s,{{ENVIRONMENT}},${ENVIRONMENT},g" $(Build.SourcesDirectory)/manifests/service.yaml

- stage: DeployToAKS
  displayName: Deploy to AKS (${{ parameters.environment }})
  dependsOn: BuildAndPush
  jobs:
  - job: Deploy
    displayName: Deploy to AKS using Kubernetes Manifests
    pool: default
    variables:
      - ${{ if eq(parameters.environment, 'dev') }}:
        - group: dev-variables
      - ${{ if eq(parameters.environment, 'qa') }}:
        - group: qa-variables
      - ${{ if eq(parameters.environment, 'uat') }}:
        - group: uat-variables
      - ${{ if eq(parameters.environment, 'prod') }}:
        - group: prod-variables
    steps:
    - checkout: self

    - task: KubernetesManifest@1
      displayName: Deploy to AKS
      inputs:
        action: 'deploy'
        connectionType: 'kubernetesServiceConnection'
        kubernetesServiceConnection: $(K8S_SERVICE_CONNECTION)  # From variable group
        namespace: 'dev'  # From variable group
        manifests: |
          $(Build.SourcesDirectory)/manifests/deployment.yaml
          $(Build.SourcesDirectory)/manifests/services.yaml
        containers: '$(CONTAINER_REGISTRY)/$(IMAGE_REPOSITORY):$(tag)'
        imagePullSecrets: 'acrpullapp1'
        overrides: |
          spec:
            template:
              spec:
                containers:
                - name: my-app-container
                  env:
                  - name: APP_ENV
                    value: "$(ENVIRONMENT)"   # From variable group
                  - name: LOG_LEVEL
                    value: "$(LOG_LEVEL)" # From variable group
