trigger:
- main

parameters:
  - name: environment
    displayName: "Select Environment"
    type: string
    default: "dev"
    values:
      - dev
      - qa
      - uat
      - prod

variables:
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  manifestsPath: '$(Build.SourcesDirectory)/kubernetes.yml'  # Single manifest for all environments
  tag: '$(Build.BuildId)'

stages:
- stage: BuildAndPush
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build and Push Docker Image to ACR
    pool:
      vmImage: 'windows-latest'
    variables:
      - ${{ if eq(parameters.environment, 'dev') }}:
        - group: dev-variables
      - ${{ if eq(parameters.environment, 'qa') }}:
        - group: qa-variables
      - ${{ if eq(parameters.environment, 'uat') }}:
        - group: uat-variables
      - ${{ if eq(parameters.environment, 'prod') }}:
        - group: prod-variables
    steps:
    - task: Docker@2
      displayName: Build and Push Docker Image
      inputs:
        command: buildAndPush
        repository: $(IMAGE_REPOSITORY)  # From variable group
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)  # From variable group
        tags: |
          $(tag)

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Kubernetes Manifests'
      inputs:
        PathtoPublish: '$(manifestsPath)'
        ArtifactName: 'kube-manifest'
        publishLocation: 'Container'

- stage: DeployToAKS
  displayName: Deploy to AKS (${{ parameters.environment }})
  dependsOn: BuildAndPush
  jobs:
  - job: Deploy
    displayName: Deploy to AKS using Kubernetes Manifests
    pool:
      vmImage: 'windows-latest'
    variables:
      - ${{ if eq(parameters.environment, 'dev') }}:
        - group: dev-variables
      - ${{ if eq(parameters.environment, 'qa') }}:
        - group: qa-variables
      - ${{ if eq(parameters.environment, 'uat') }}:
        - group: uat-variables
      - ${{ if eq(parameters.environment, 'prod') }}:
        - group: prod-variables
    steps:
    - checkout: self

    - task: KubernetesManifest@1
      displayName: Deploy to AKS
      inputs:
        action: 'deploy'
        connectionType: 'kubernetesServiceConnection'
        kubernetesServiceConnection: $(K8S_SERVICE_CONNECTION)  # From variable group
        namespace: $(NAMESPACE)  # From variable group
        manifests: '$(manifestsPath)'
        containers: '$(CONTAINER_REGISTRY)/$(IMAGE_REPOSITORY):$(tag)'
        imagePullSecrets: 'acrpullapp1'
        overrides: |
          spec:
            template:
              spec:
                containers:
                - name: my-app-container
                  env:
                  - name: APP_ENV
                    value: "$(APP_ENV)"   # From variable group
                  - name: LOG_LEVEL
                    value: "$(LOG_LEVEL)" # From variable group