trigger: none

parameters:
  - name: environment
    displayName: "Select Environment"
    type: string
    default: "dev"
    values:
      - dev
      - qa
      - uat
      - prod

variables:
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  APP_NAME: '$(Build.Repository.Name)'  # App name same as repo name
  manifestsPath: '$(Build.SourcesDirectory)/manifests/'
  IMAGE_REPOSITORY: '$(Build.Repository.Name)'
  RESOURCE_GROUP: 'spoke1-rg'  # Update with your AKS resource group
  CLUSTER_NAME: 'dev-aks-cluster'  # Update with your AKS cluster name
  AZURE_SUBSCRIPTION: 'my-azure-service-connection'  # Set this to the name of your service connection
  K8S_SERVICE_CONNECTION: 'myakscred'  # Kubernetes service connection name (if applicable)

stages:

- stage: BuildAndPush
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build and Push Docker Image to ACR
    pool: default
    steps:
    - task: Docker@2
      displayName: Build and Push Docker Image
      inputs:
        command: buildAndPush
        repository: $(IMAGE_REPOSITORY)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Kubernetes Manifests'
      inputs:
        PathtoPublish: '$(manifestsPath)'
        ArtifactName: 'kube-manifest'
        publishLocation: 'Container'

- stage: DeployToAKS
  displayName: Deploy to AKS (${{ parameters.environment }})
  dependsOn: BuildAndPush
  jobs:
  - job: Deploy
    displayName: Deploy to AKS using Kubernetes Manifests
    pool: default
    steps:

    # Azure Login and Get AKS Credentials Using Service Connection
    - task: AzureCLI@2
      displayName: 'Login to Azure and Get AKS Credentials'
      inputs:
        azureSubscription: '$(AZURE_SUBSCRIPTION)'  # Using Azure Service Connection (Set to name of your Azure service connection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Logging into Azure..."
          az aks get-credentials --resource-group $(RESOURCE_GROUP) --name $(CLUSTER_NAME) --overwrite-existing
          kubectl config current-context
          kubectl get nodes -o wide
          kubectl get secret -n default

    - task: DownloadBuildArtifacts@0
      displayName: 'Download Kubernetes Manifests'
      inputs:
        artifactName: 'kube-manifest'
        downloadPath: '$(Build.SourcesDirectory)/manifests/'

     # Debugging Step: print APP_NAME
    - script: |
        echo $(APP_NAME)
      displayName: 'Print APP_NAME'

     # Debugging Step: print IMAGE_REPOSITORY
    - script: |
        echo $(IMAGE_REPOSITORY)
      displayName: 'Print IMAGE_REPOSITORY'
    
       # Debugging Step: print $(Build.Repository.Name)
    - script: |
        echo $(Build.Repository.Name)
      displayName: 'Print IMAGE_REPOSITORY'

    # Debugging Step: Ensure Variables Are Replaced in the Manifest
    - script: |
        sed -i "s,{{APP_NAME}},$(echo $(APP_NAME) | tr '[:upper:]' '[:lower:]')," $(Build.SourcesDirectory)/manifests/deployment.yaml
        sed -i "s,{{CONTAINER_REGISTRY}},$(CONTAINER_REGISTRY)," $(Build.SourcesDirectory)/manifests/deployment.yaml
        sed -i "s,{{IMAGE_REPOSITORY}},$(echo $(IMAGE_REPOSITORY) | tr '[:upper:]' '[:lower:]')," $(Build.SourcesDirectory)/manifests/deployment.yaml
        sed -i "s,{{tag}},$(tag)," $(Build.SourcesDirectory)/manifests/deployment.yaml
        echo "=== Debug: Deployment YAML ==="
        cat $(Build.SourcesDirectory)/manifests/deployment.yaml
      displayName: 'Replace Variables in Manifest & Debug'

    # Debugging Step: Verify Kubernetes Permissions
    - script: |
        kubectl config view --minify
        kubectl get serviceaccount default -n dev
      displayName: 'Check Kubernetes Permissions'

    # Deploy to AKS using the default service account (in dev namespace)
    - task: KubernetesManifest@1
      displayName: Deploy to AKS using serviceaccount:dev:default
      inputs:
        action: 'deploy'
        connectionType: 'kubernetesServiceConnection'
        kubernetesServiceConnection: $(K8S_SERVICE_CONNECTION)  # Kubernetes Service Connection name'  # Use environment parameter to set the namespace (dev, qa, etc.)
        manifests: |
          $(Build.SourcesDirectory)/manifests/deployment.yaml
