apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{APP_NAME}}
  namespace: {{ENVIRONMENT}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{APP_NAME}}
  template:
    metadata:
      labels:
        app: {{APP_NAME}}
    spec:
      imagePullSecrets:
        - name: acrpull-secretnew  # Reference the secret created
      containers:
      - name: my-app-container
        image: APP_IMAGE_NAME
        ports:
        - containerPort: 8080
        env:
        - name: APP_ENV
          value: "{{ENVIRONMENT}}"
        - name: LOG_LEVEL
          value: "{{LOG_LEVEL}}"
