apiVersion: apps/v1
kind: Deployment
metadata:
  name: myappmulti-{{ENVIRONMENT}}  # Ensure this variable is properly replaced
  labels:
    app: {{APP_NAME}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{APP_NAME}}
  template:
    metadata:
      labels:
        app: {{APP_NAME}}
    spec:
      containers:
      - name: {{APP_NAME}}
        image: APP_IMAGE_NAME
        ports:
        - containerPort: 8080
