apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{APP_NAME}}-deployment
  labels:
    app: {{APP_NAME}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{APP_NAME}}
  template:
    metadata:
      labels:
        app: {{APP_NAME}}
    spec:
      containers:
        - name: {{APP_NAME}}  # Fixed the missing closing quote
          image: "{{CONTAINER_REGISTRY}}/{{IMAGE_REPOSITORY}}:{{tag}}"
          imagePullPolicy: Always
          env:
            - name: APP_ENV
              value: {{APP_NAME}}
          ports:
            - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: {{APP_NAME}}-service
spec:
  selector:
    app: {{APP_NAME}}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # This creates a public IP for the service
